apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cookie-backend
  name: cookie-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cookie-backend
  strategy: {}
  template:
    metadata:
      labels:
        app: cookie-backend
    spec:
      containers:
      - image: ghcr.io/hlvm04/simple-fortune-cookie/backend:latest
        name: backend
        env:
        - name: REDIS_DNS
          value: localhost
        resources: {}
      - image: redis:8.10-alpine
        name: redis
        resources: {}
