apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cookie-backend
  name: cookie-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cookie-backend
  strategy: {}
  template:
    metadata:
      labels:
        app: cookie-backend
    spec:
      containers:
      - image: ghcr.io/hlvm04/simple-fortune-cookie/backend:latest
        name: backend
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65532
        env:
        - name: REDIS_DNS
          value: cookie-redis
        resources: {}
