name: main
on: push
jobs:
  Build:
    runs-on: ubuntu-slim
    container: golang:1.26-alpine
    steps:
      - name: Clone down repository
        uses: actions/checkout@v7
      - parallel:
          - name: Build backend
            run: docker/build-push-action@v7
            with: 
              push: false
              context: backend
          - name: Build frontend
            run: docker/build-push-action@v7
            with: 
              push: false
              context: frontend

  Test:
    runs-on: ubuntu-slim
    container: golang:1.26-alpine
    steps:
      - name: Clone down repository
        uses: actions/checkout@v7
      - name: Run frontend tests
        run: go test frontend
      
        
