name: main
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    container: golang:1.26-alpine
    steps:
      - name: Clone down repository
        uses: actions/checkout@v7
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - parallel:
          - name: Build backend
            uses: docker/build-push-action@v7
            with:
              push: false
              context: backend
          - name: Build frontend
            uses: docker/build-push-action@v7
            with:
              push: false
              context: frontend

  Test:
    runs-on: ubuntu-latest
    container: golang:1.26-alpine
    steps:
      - name: Clone down repository
        uses: actions/checkout@v7
      - name: Run frontend tests
        run: go test frontend
